<%@ Page Title="Edit Data" Language="C#" MasterPageFile="~/Styles/Site.Master" AutoEventWireup="true" CodeBehind="EditData.aspx.cs" Inherits="Cookiepedia.EditData" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div>
       <asp:SqlDataSource ID="sdsCatalogue" runat="server" 
     ConnectionString="<%$ ConnectionStrings:CookiesDbConnectionString %>" 
     SelectCommand="SELECT [Ref_ID], [Name], [Description] FROM 
       [T_Catalogue]"            
     UpdateCommand="UPDATE [T_Catalogue] SET [Name] = 
       @Name, [Description] = @Description WHERE [Ref_ID] = @Ref_ID" 
     DeleteCommand="DELETE FROM [T_Catalogue] WHERE [Ref_ID] = 
       @Ref_ID">
     <DeleteParameters>
        <asp:Parameter Name="Ref_ID" Type="Int32" />
      </DeleteParameters>
      <UpdateParameters>
        <asp:Parameter Name="Name" Type="String" />
        <asp:Parameter Name="Ref_ID" Type="Int32" />
      </UpdateParameters>
    </asp:SqlDataSource>
        <asp:GridView ID="gvCatalogue" DataSourceID="sdsCatalogue"
            DataKeyNames="Ref_ID"
            AutoGenerateDeleteButton="True" runat="server" AutoGenerateColumns="False" OnSelectedIndexChanged="gvCatalogue_SelectedIndexChanged">
            <Columns>
                <asp:CommandField HeaderText="Action" ShowEditButton="True" />
                <asp:BoundField DataField="Ref_ID" HeaderText="Ref_ID" InsertVisible="False" ReadOnly="True" SortExpression="Ref_ID" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            </Columns>
        </asp:GridView>

    </div>
</asp:Content>
